FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Controllers/NutritionController.cs
using System.Threading.Tasks;
using AutoMapper;
using FitnessSuperiorMvc.BLL.Dto.Programs.Nutrition;
using FitnessSuperiorMvc.DA.Entities.Nutrition;
using FitnessSuperiorMvc.Services.People;
using FitnessSuperiorMvc.Services.Programs;
using FitnessSuperiorMvc.WEB.ViewModels.Page;
using FitnessSuperiorMvc.WEB.ViewModels.Services.Nutrition;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FitnessSuperiorMvc.WEB.Controllers
{
    [Authorize]
    public class NutritionController : Controller
    {
        private readonly FoodService _foodService;
        private readonly MealPlanService _mealPlanService;
        private readonly NutritionProgramService _nutritionProgramService;

        private readonly NutritionistService _nutritionistService;
        private readonly UserService _userService;

        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMapper _mapper;

        public NutritionController(
            FoodService foodService,
            MealPlanService mealPlanService,
            NutritionProgramService nutritionProgramService,
            UserManager<IdentityUser> userManager,
            IMapper mapper,
            NutritionistService nutritionistService, UserService userService)
        {
            _foodService = foodService;
            _mealPlanService = mealPlanService;
            _nutritionProgramService = nutritionProgramService;
            _userManager = userManager;
            _mapper = mapper;
            _nutritionistService = nutritionistService;
            _userService = userService;
        }
        [HttpGet]
        public async Task<IActionResult> FoodView(int id, string returnUrl)
        {
            var food = Task.Run(() => _foodService.GetById(id));
            ViewBag.ReturnUrl = returnUrl;
            return View(await food);
        }
        [HttpGet]
        public async Task<IActionResult> MealPlanView(int id, string returnUrl)
        {
            var complex = await Task.Run(() => _mealPlanService.GetById(id));

            ViewBag.ReturnUrl = returnUrl;
            return View(complex);
        }
        [HttpGet]
        public async Task<IActionResult> NutritionProgramView(int id, string returnUrl)
        {
            var programFromDb = await Task.Run(() => _nutritionProgramService.GetById(id));

            ViewBag.ReturnUrl = returnUrl;
            return View(programFromDb);
        }
        [HttpGet]
        [Authorize(Roles= "Nutritionist")]
        public IActionResult CreateFood()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Nutritionist")]
        public IActionResult CreateFood(FoodViewModel model)
        {
            if (!ModelState.IsValid) return View();
                _foodService.Create(_mapper.Map<Food>
                (
                        new FoodDto(
                            model.Name,
                            model.Calories,
                            model.BeneficialFeatures,
                            model.Proteins,
                            model.Fats,
                            model.Carbohydrates)
                ));
            return RedirectToAction("SuccessfulCreation", "Validation", new { type = "food", name = model.Name });

        }
        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public IActionResult CreateMealPlan()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> CreateMealPlan(MealPlanViewModel model)
        {
            if (!ModelState.IsValid) return View();
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));

            var food = await Task.Run(() => _foodService.GetAddingFood(user));
            var mealDto = new MealPlanDto(model.Name, model.Description);
            MealPlan mealPlan = _mapper.Map<MealPlan>(mealDto);
            mealPlan.Food = food;
            mealPlan.Author = user;
            _mealPlanService.Create(mealPlan);
            _foodService.DeleteAddingFood(user);
            return RedirectToAction("SuccessfulCreation", "Validation", new { type = "meal plan", name = model.Name });

        }
        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public IActionResult CreateProgram()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> CreateProgram(NutritionProgramViewModel model)
        {
            if (!ModelState.IsValid) return View();
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));

            var mealPlans = await Task.Run(() => _nutritionProgramService.GetAddingMealPlans(user));

            var programDto = new NutritionProgramDto(
                model.Name,
                model.Description,
                model.Destination,
                model.Price,
                model.TypeOfDiet);
            NutritionProgram nutritionProgram = _mapper.Map<NutritionProgram>(programDto);
            nutritionProgram.MealPlans = mealPlans;
            nutritionProgram.Nutritionist = user;
            _nutritionProgramService.Create(nutritionProgram);
            _nutritionProgramService.DeleteAddingMealPlans(user);
            return RedirectToAction("SuccessfulCreation", "Validation",
                new { type = "nutrition program", name = model.Name });
        }
        public IActionResult ExistingFood(int page = 1)
        {
            var programView = new PaginationViewModel<Food>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = _foodService.GetAll(),
                CurrentPage = page
            };
            return View(programView);
        }
        public IActionResult ExistingMealPlans(int page = 1)
        {
            var programView = new PaginationViewModel<MealPlan>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = _mealPlanService.GetAll(),
                CurrentPage = page
            };
            return View(programView);
        }
        public IActionResult ExistingPrograms(int page = 1)
        {
            var programView = new PaginationViewModel<NutritionProgram>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = _nutritionProgramService.GetAll(),
                CurrentPage = page
            };
            return View(programView);
        }
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyPrograms(int page)
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));
            var programs = Task.Run(() => _nutritionProgramService.GetNutritionPrograms(user.Id));
            var programView = new PaginationViewModel<NutritionProgram>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = await programs,
                CurrentPage = page
            };
            return View(programView);
        }
    }
}

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Controllers/WorkoutController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using FitnessSuperiorMvc.BLL.Dto.Programs.Sport;
using FitnessSuperiorMvc.DA.Entities.Sport;
using FitnessSuperiorMvc.Services.People;
using FitnessSuperiorMvc.Services.Programs;
using FitnessSuperiorMvc.WEB.ViewModels.Page;
using FitnessSuperiorMvc.WEB.ViewModels.Services.Sport;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FitnessSuperiorMvc.WEB.Controllers
{
    [Authorize]
    public class WorkoutController : Controller
    {
        private readonly ExerciseService _exerciseService;
        private readonly SetOfExercisesService _setOfExercisesService;
        private readonly TrainingProgramsService _trainingProgramsService;

        private readonly TrainerService _trainerService;
        private readonly UserService _userService;

        private readonly CalendarService _calendarService;

        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMapper _mapper;
        public WorkoutController(
            IMapper mapper,
            UserManager<IdentityUser> userManager,
            ExerciseService exerciseService,
            SetOfExercisesService setOfExercisesService, 
            TrainingProgramsService trainingProgramsService,
            TrainerService trainerService,
            UserService userService,
            CalendarService calendarService)
        {
            _mapper = mapper;
            _userManager = userManager;
            _exerciseService = exerciseService;
            _setOfExercisesService = setOfExercisesService;
            _trainingProgramsService = trainingProgramsService;
            _trainerService = trainerService;
            _userService = userService;
            _calendarService = calendarService;
        }
        [HttpGet]
        public async Task<IActionResult> ExerciseView(int id, string returnUrl)
        {

            var exercise = Task.Run(() => _exerciseService.GetById(id));
            ViewBag.ReturnUrl = returnUrl;
            return View(await exercise);
        }
        [HttpGet]
        public async Task<IActionResult> ComplexView(int id, string returnUrl)
        {
            var complex = await Task.Run(() => _setOfExercisesService.GetById(id));
            
            ViewBag.ReturnUrl = returnUrl;
            return View(complex);
        }
        [HttpGet]
        public async Task<IActionResult> TrainingProgramView(int id, string returnUrl)
        {
            var programFromDb = await Task.Run(() => _trainingProgramsService.GetById(id));
            
            ViewBag.ReturnUrl = returnUrl;
            return View(programFromDb);
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public IActionResult CreateExercise()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Trainer")]
        public IActionResult CreateExercise(ExerciseViewModel exerciseViewModel)
        {
            if (!ModelState.IsValid) return View();
            if (string.IsNullOrWhiteSpace(exerciseViewModel.YoutubeUrl))
            {
                _exerciseService.Create(_mapper.Map<Exercise>
                (
                new ExerciseDto(
                    exerciseViewModel.Name,
                    exerciseViewModel.MuscleGroups,
                    exerciseViewModel.Description))
                );
            }
            else
            {
                _exerciseService.Create(_mapper.Map<Exercise>
                    (
                    new ExerciseDto(
                        exerciseViewModel.Name,
                        exerciseViewModel.MuscleGroups,
                        exerciseViewModel.Description,
                        exerciseViewModel.YoutubeUrl))
                    );
            }
            return RedirectToAction("SuccessfulCreation", "Validation", new { type = "exercise", name = exerciseViewModel.Name });
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public IActionResult CreateComplex()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> CreateComplex(SetOfExerciseViewModel model)
        {
            if (!ModelState.IsValid) return View();
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));

            var exercises = await Task.Run(() => _exerciseService.GetAddingExercises(user));
            var setDto = new SetOfExercisesDto(model.Name, model.MuscleGroups, model.Description);
            SetOfExercises set = _mapper.Map<SetOfExercises>(setDto);
            set.Exercises = exercises;
            set.Author = user;
            _setOfExercisesService.Create(set);
            _exerciseService.DeleteAddingExercises(user);
            return RedirectToAction("SuccessfulCreation", "Validation", new { type = "set of exercises", name = model.Name });
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public IActionResult CreateProgram()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> CreateProgram(TrainingProgramViewModel model)
        {
            if (!ModelState.IsValid) return View();
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));

            var complexes = await Task.Run(() => _trainingProgramsService.GetAddingComplexes(user));

            var programDto = new TrainingProgramDto(
                model.Name,
                model.Description,
                model.Destination,
                model.Price,
                model.TypeOfProgram,
                model.RequiredSkillLevel,
                model.AgeRestriction);
            TrainingProgram trainingProgram = _mapper.Map<TrainingProgram>(programDto);
            trainingProgram.SetsOfExercises = complexes;
            trainingProgram.Trainer = user;
            _trainingProgramsService.Create(trainingProgram);
            _trainingProgramsService.DeleteAddingComplexes(user);
            return RedirectToAction("SuccessfulCreation", "Validation",
                new { type = "training program", name = model.Name });

        }
        [HttpGet]
        public async Task<IActionResult> ExistingExercises(int page = 1)
        {
            var getData = Task.Run(() => _exerciseService.GetAll());
            var exerciseView = new PaginationViewModel<Exercise>()
            {
                WorkoutPerPage = 5,
                ExistingPrograms = await getData,
                CurrentPage = page
            };
            return View(exerciseView);
        }
        [HttpGet]
        public async Task<IActionResult> ExistingComplexes(int page = 1)
        {
            var getData = Task.Run(() => _setOfExercisesService.GetAll());
            var exerciseView = new PaginationViewModel<SetOfExercises>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = await getData,
                CurrentPage = page
            };
            return View(exerciseView);
        }
        [HttpGet]
        public async Task<IActionResult> ExistingPrograms(int page = 1)
        {
            var getData = Task.Run(() => _trainingProgramsService.GetAll());
            var programView = new PaginationViewModel<TrainingProgram>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = await getData,
                CurrentPage = page
            };
            return View(programView);
        }
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyPrograms(int page)
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));
            var programs = Task.Run(() => _trainingProgramsService.GetTrainingPrograms(user.Id));
            var programView = new PaginationViewModel<TrainingProgram>()
            {
                WorkoutPerPage = 3,
                ExistingPrograms = await programs,
                CurrentPage = page
            };
            return View(programView);
        }
        //TODO: Move Calendar and Get Event in another controller
        [HttpGet]
        public IActionResult Calendar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetEvents()
        {
           var events = _calendarService.GetAll();
           return new JsonResult(events);
        }
    }
}

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Views/List/ComplexesInProgram.cshtml
@using FitnessSuperiorMvc.BLL.Dto.Programs.Sport
@using FitnessSuperiorMvc.DA.Entities.Sport
@model List<FitnessSuperiorMvc.DA.Entities.Sport.SetOfExercises>

<div class="main__content m-height">
    <div class="main__title center">
        Add complex to program
    </div>
    <div class="adding-container">
        @if (Model.Any())
        {
            <table class="table" style="color: #ccc">
                <tr>
                    <th>Name</th>
                    <th>MuscleGroup</th>
                    <th></th>
                </tr>
                @foreach (SetOfExercises complex in Model)
                {
                    <tr>
                        <td>@complex.Name</td>
                        <td>@complex.MuscleGroups</td>
                        <td><a asp-action="RemoveComplexFromProgram" asp-route-id="@complex.Id" class="cross">&#10008;</a></td>
                    </tr>
                }
            </table>
        }
       
        <div class="d-flex justify-content-between">
            <a class="grey-btn" asp-action="ExistingComplexes" asp-controller="Workout">Add complex</a>
            @if (Model.Count < 1)
            {
                <a class="grey-btn-disabled" title="At least 1 complex">Create Program (At least 1 complex)</a>
            }
        
            else
            {
                <a class="grey-btn" asp-action="CreateProgram" asp-controller="Workout">Create program</a>
            }
        
        </div>
    </div>
</div>

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Views/List/ExercisesInComplex.cshtml
@using FitnessSuperiorMvc.DA.Entities.Sport
@model List<FitnessSuperiorMvc.DA.Entities.Sport.Exercise>

<div class="main__content m-height">
    <div class="main__title center">
        Add exercise to complex
    </div>
    <div class="adding-container">
        @if (Model.Any())
        {
            <table class="table" style="color: #ccc">
                <tr>
                    <th>Name</th>
                    <th>MuscleGroup</th>
                    <th></th>
                </tr>
                @foreach (Exercise exercise in Model)
                {
                    <tr>
                        <td>@exercise.Name</td>
                        <td>@exercise.MuscleGroups</td>
                        <td><a asp-action="RemoveExerciseFromComplex" asp-route-id="@exercise.Id" class="cross">&#10008;</a></td>
                    </tr>
                }
            </table>
        }
       
    <div class="d-flex justify-content-between">
        <a class="grey-btn" asp-action="ExistingExercises" asp-controller="Workout">Add exercise</a>
        @if (Model.Count < 3)
        {
            <a class="grey-btn-disabled" title="At least 3 exercises">Create complex (At least 3 exercises)</a>
        }
        
        else
        {
            <a class="grey-btn" asp-action="CreateComplex" asp-controller="Workout">Create complex</a>
        }
        
    </div>
    </div>
</div>

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Views/List/FoodInMealPlan.cshtml
@using FitnessSuperiorMvc.DA.Entities.Nutrition
@model List<FitnessSuperiorMvc.DA.Entities.Nutrition.Food>

<div class="main__content m-height">
    <div class="main__title center">
        Add food to meal plan
    </div>
    <div class="adding-container">
        @if (Model.Any())
        {
            <table class="table" style="color: #ccc">
                <tr>
                    <th>Name</th>
                    <th>Calories</th>
                    <th></th>
                </tr>
                @foreach (Food food in Model)
                {
                    <tr>
                        <td>@food.Name</td>
                        <td>@food.Calories</td>
                        <td><a asp-action="RemoveFoodFromMealPlan" asp-route-id="@food.Id" class="cross">&#10008;</a></td>
                    </tr>
                }
            </table>
        }
       
        <div class="d-flex justify-content-between">
            <a class="grey-btn" asp-action="ExistingFood" asp-controller="Nutrition">Add food</a>
            @if (Model.Count < 3)
            {
                <a class="grey-btn-disabled" title="At least 3 food">Create meal plan (At least 3 food)</a>
            }
        
            else
            {
                <a class="grey-btn" asp-action="CreateMealPlan" asp-controller="Nutrition">Create meal plan</a>
            }
        
        </div>
    </div>
</div>

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Views/List/MealPlansInProgram.cshtml
@using FitnessSuperiorMvc.DA.Entities.Nutrition
@model List<FitnessSuperiorMvc.DA.Entities.Nutrition.MealPlan>

<div class="main__content m-height">
    <div class="main__title center">
        Add meal plan to program
    </div>
    <div class="adding-container">
        @if (Model.Any())
        {
            <table class="table" style="color: #ccc">
                <tr>
                    <th>Name</th>
                    <th>Calories</th>
                    <th></th>
                </tr>
                @foreach (MealPlan mealPlan in Model)
                {
                    <tr>
                        <td>@mealPlan.Name</td>
                        <td>@mealPlan.Calories</td>
                        <td><a asp-action="RemoveMealPlanFromProgram" asp-route-id="@mealPlan.Id" class="cross">&#10008;</a></td>
                    </tr>
                }
            </table>
        }

        <div class="d-flex justify-content-between">
            <a class="grey-btn" asp-action="ExistingMealPlans" asp-controller="Nutrition">Add meal plan</a>
            @if (Model.Count < 1)
            {
                <a class="grey-btn-disabled" title="At least 1 meal plan">Create Program (At least 1 meal plan)</a>
            }

            else
            {
                <a class="grey-btn" asp-action="CreateProgram" asp-controller="Nutrition">Create program</a>
            }

        </div>
    </div>
</div>