FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Controllers/CommunityController.cs
using Microsoft.AspNetCore.Mvc;

namespace FitnessSuperiorMvc.WEB.Controllers
{
    public class CommunityController : Controller
    {
        [HttpGet]
        public IActionResult MyReview()
        {
            return View();
        }
    }
}

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Controllers/ListController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using FitnessSuperiorMvc.Services.People;
using FitnessSuperiorMvc.Services.Programs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FitnessSuperiorMvc.WEB.Controllers
{
    public class ListController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        private readonly ExerciseService _exerciseService;
        private readonly SetOfExercisesService _setOfExercisesService;
        private readonly TrainingProgramsService _trainingProgramsService;


        private readonly FoodService _foodService;
        private readonly MealPlanService _mealPlanService;
        private readonly NutritionProgramService _nutritionProgramService;

        private readonly TrainerService _trainerService;
        private readonly NutritionistService _nutritionistService;
        private readonly UserService _userService;

        public ListController(
            UserManager<IdentityUser> userManager,
            ExerciseService exerciseService,
            SetOfExercisesService setOfExercisesService,
            FoodService foodService,
            MealPlanService mealPlanService,
            TrainerService trainerService,
            NutritionistService nutritionistService,
            UserService userService,
            TrainingProgramsService trainingProgramsService,
            NutritionProgramService nutritionProgramService)
        {
            _userManager = userManager;
            _exerciseService = exerciseService;
            _setOfExercisesService = setOfExercisesService;
            _foodService = foodService;
            _mealPlanService = mealPlanService;
            _trainerService = trainerService;
            _nutritionistService = nutritionistService;
            _userService = userService;
            _trainingProgramsService = trainingProgramsService;
            _nutritionProgramService = nutritionProgramService;
        }
        [HttpGet]
        public async Task<IActionResult> ExercisesInComplex()
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));
            var exercises =await Task.Run(()=>_exerciseService.GetAddingExercises(user));
            return View(exercises);
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> AddExerciseToComplex(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));
            var exercise = await Task.Run(()=>_exerciseService.GetById(id));
            await Task.Run(() => _exerciseService.AddAddingExercises(exercise, user));
            return RedirectToAction("ExercisesInComplex");
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> RemoveExerciseFromComplex(int id)
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));
            await Task.Run(()=>_exerciseService.RemoveAddingExercises(id,user));
            return RedirectToAction("ExercisesInComplex");
        }

        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> ComplexesInProgram()
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));
            var complexes = await Task.Run(() => _setOfExercisesService.GetAddingComplexes(user));
            return View(complexes);
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> AddComplexToProgram(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));
            var complex = await Task.Run(()=>_setOfExercisesService.GetById(id));
            await Task.Run(() => _setOfExercisesService.AddAddingComplexes(complex, user));
            return RedirectToAction("ComplexesInProgram");
        }
        [HttpGet]
        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> RemoveComplexFromProgram(int id)
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _trainerService.GetByIdentityId(userId));
            await Task.Run(() => _setOfExercisesService.RemoveAddingComplexes(id, user));
            return RedirectToAction("ComplexesInProgram");
        }
        [HttpGet]
        public async Task<IActionResult> FoodInMealPlan()
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));
            var food = await Task.Run(() => _foodService.GetAddingFood(user));
            return View(food);
        }
        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> AddFoodInMealPlan(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));
            var food = await Task.Run(() => _foodService.GetById(id));
            await Task.Run(() => _foodService.AddAddingFood(food, user));
            return RedirectToAction("FoodInMealPlan");
        }
        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> RemoveFoodFromMealPlan(int id)
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));
            await Task.Run(() => _foodService.RemoveAddingFood(id, user));
            return RedirectToAction("FoodInMealPlan");
        }

        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> MealPlansInProgram()
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));
            var mealPlans = await Task.Run(() => _mealPlanService.GetAddingMealPlans(user));
            return View(mealPlans);
        }
        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> AddMealPlanToProgram(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));
            var mealPlan = await Task.Run(() => _mealPlanService.GetById(id));
            await Task.Run(() => _mealPlanService.AddAddingMealPlans(mealPlan, user));
            return RedirectToAction("MealPlansInProgram");
        }
        [HttpGet]
        [Authorize(Roles = "Nutritionist")]
        public async Task<IActionResult> RemoveMealPlanFromProgram(int id)
        {
            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _nutritionistService.GetByIdentityId(userId));
            await Task.Run(() => _mealPlanService.RemoveAddingMealPlan(id, user));
            return RedirectToAction("MealPlansInProgram");
        }

        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> AddTrainingProgramToUser(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));
            
            var program = await Task.Run(() => _trainingProgramsService.GetById(id));
            user.TrainingPrograms.Add(program);
            await Task.Run(() => _userService.Update(user));

            return RedirectToAction("MyPrograms","Workout");
        }
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> RemoveTrainingProgramInUser(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));

            var program = await Task.Run(() => _trainingProgramsService.GetById(id));
            user.TrainingPrograms.Remove(program);
            await Task.Run(() => _userService.Update(user));

            return RedirectToAction("MyPrograms", "Workout");
        }
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> AddNutritionProgramToUser(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));

            var program = await Task.Run(() => _nutritionProgramService.GetById(id));
            user.NutritionPrograms.Add(program);
            await Task.Run(() => _userService.Update(user));

            return RedirectToAction("MyPrograms", "Nutrition");
        }
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> RemoveNutritionProgramInUser(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));

            var program = await Task.Run(() => _nutritionProgramService.GetById(id));
            user.NutritionPrograms.Remove(program);
            await Task.Run(() => _userService.Update(user));

            return RedirectToAction("MyPrograms", "Nutrition");
        }
        [HttpGet]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> AddTrainingProgramToCalendar(int id)
        {

            var userId = _userManager.GetUserId(User);
            var user = await Task.Run(() => _userService.GetByIdentityId(userId));

            var program = await Task.Run(() => _trainingProgramsService.GetById(id));
            user.TrainingPrograms.Remove(program);

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Controllers/ResourcesController.cs
using Microsoft.AspNetCore.Mvc;

namespace FitnessSuperiorMvc.WEB.Controllers
{
    public class ResourcesController : Controller
    {
        [HttpGet]
        public IActionResult Workout()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Nutrition()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Rest()
        {
            return View();
        }
    }
}

FitnessSuperiorMvc/FitnessSuperiorMvc.WEB/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A website that will help you become healthier.
          Author: Klos Maksym, ">
    <meta name="theme-color" content="#340647">
    <title>@ViewData["Title"] - FitnessSuperiorMvc</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@500&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="~/images/FS.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/images/FS.ico">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-xxl">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" alt="logo" class="logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Workouts
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (User.IsInRole("Trainer"))
                                {
                                    <li><a class="dropdown-item" asp-controller="Workout" asp-action="CreateExercise">Create exercise</a></li>
                                    <li><a class="dropdown-item" asp-controller="List" asp-action="ExercisesInComplex">Create set of exercises</a></li>
                                    <li><a class="dropdown-item" asp-controller="List" asp-action="ComplexesInProgram">Create training program</a></li>
                                }
                                <li><a class="dropdown-item" asp-controller="Workout" asp-action="ExistingPrograms">Existing programs</a></li>
                                @if (User.IsInRole("User"))
                                {
                                    <li><a class="dropdown-item" asp-controller="Workout" asp-action="MyPrograms">My programs</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="Workout" asp-action="Calendar">Calendar</a></li>
                                }

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Nutrition
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (User.IsInRole("Nutritionist"))
                                {
                                    <li><a class="dropdown-item" asp-controller="Nutrition" asp-action="CreateFood">Create food</a></li>
                                    <li><a class="dropdown-item" asp-controller="List" asp-action="FoodInMealPlan">Create meal plan</a></li>
                                    <li><a class="dropdown-item" asp-controller="List" asp-action="MealPlansInProgram">Create nutrition</a></li>
                                }
                                <li><a class="dropdown-item" asp-controller="Nutrition" asp-action="ExistingPrograms">Existing programs</a></li>
                                @if (User.IsInRole("User"))
                                {
                                    <li><a class="dropdown-item" asp-controller="Nutrition" asp-action="MyPrograms">My programs</a></li>
                                }

                            </ul>
                        </li>
                        @if (!User.IsInRole("User") && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Community
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Community" asp-action="MyReview">My reviews</a></li>
                                </ul>
                            </li>
                        }

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Resources
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Resources" asp-action="Workout">Workout</a></li>
                                <li><a class="dropdown-item" asp-controller="Resources" asp-action="Nutrition">Nutrition</a></li>
                                <li><a class="dropdown-item" asp-controller="Resources" asp-action="Rest">Rest</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                About
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="About" target="Information about the site.">Learn more</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#contact">Contact us</a></li>
                            </ul>
                        </li>
                    </ul>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <div class="d-flex">
                            <a class="sign-in-link sign-link" asp-controller="Account" asp-action="Login">Sign in</a>
                            <a class="sign-up-link sign-link" asp-controller="Account" asp-action="Register">Sign up</a>
                        </div>
                    }
                    else
                    {
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" style="text-transform: none;" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Profile">Profile</a></li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="CreateRole">Create role</a></li>
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="Users">Assign user role</a></li>
                                    }

                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
                                </ul>
                            </li>
                        </ul>

                    }
                    @*<ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" style="text-transform: none;" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Profile
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="CreateRole">Create role</a></li>
                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="Users">Assign user role</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
                                </ul>
                            </li>
                        </ul>*@
                </div>
            </div>
        </nav>
        <partial name="~/Views/Home/_ContactUs.cshtml" />
    </header>
    <main role="main" class="pb-3">
        <div class="container-xxl">
            @RenderBody()

        </div>
    </main>

    <footer class="footer text-muted">
        <div class="container nav-link">
            &copy; 2021 - Fitness Superior - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src='~/js/form-validation.js'></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>